# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.customize ["modifyvm", :id, "--memory", 512]

  servers = {
    :riak01 => {:network => "12.0.0.20"},
    :riak02 => {:network => "12.0.0.21"},
  }

  servers.each do |name, opts|
	  config.vm.define name do |riak| 
	    riak.vm.box = "precise64"
	    riak.vm.box_url = "http://files.vagrantup.com/precise64.box"
	    riak.vm.network :hostonly, opts[:network]
#	    riak.vm.network :bridged
	    riak.vm.provision :puppet, :facter => { "riak_name" => "riak@#{opts[:network]}", "riak_ip" => "#{opts[:network]}" }  do |puppet|
	      puppet.manifests_path = "manifests"
	      puppet.manifest_file  = "riak.pp"
	    end
	  end
  end  
end
